version: '3.8'

services:
  npm-stats:
    build: .
    container_name: npm-stats
    restart: unless-stopped
    ports:
      - "5000:5000"
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
